name: Test Runner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up JDK 11 for the project
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Set up the browser (Firefox in this case)
      - uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: firefox
          version: latest

      # Run Maven tests with both environment variables and -D flags
      - name: Run tests
        run: mvn clean test
        env:
          USER: ${{ secrets.SD_USER }}      # GitHub secret for username
          PASSWORD: ${{ secrets.SD_PASSWORD }}  # GitHub secret for password
