name: Test Runner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Install Firefox and GeckoDriver
      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt update
          sudo apt install -y firefox-esr
          wget https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.31.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      # Install Xvfb (for headless testing)
      - name: Install Xvfb
        run: |
          sudo apt-get install -y xvfb

      # Start Xvfb to simulate the X11 display
      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 &

      # Run tests
      - name: Run tests
        run: mvn clean test

